name: bviformer
channels:
  - pytorch
  - conda-forge 
  - defaults
dependencies:
  - Python 3.8.20
  - pip
  - pip:
      - numpy>=1.23
      - pillow>=10.4.0
      - tqdm>=4.67.1
      - pyyaml>=6.0.2
      - opencv-python>=4.10.0.84
      - scikit-image>=0.21.0
      - torch==1.10+cuda
      - torchvision==0.11.1+cuda
